[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
dioxus = { workspace = true, features = ["fullstack"] }
rusqlite = { version = "0.32.0", optional = true, features = ["chrono"] }
serde = { version = "1.0.228", features = ["derive"] }

[features]
server = ["dioxus/server", "dep:rusqlite"]
